name: Build

on:
  pull_request:
    branches:
      - development

  push:
    branches:
      - development

jobs:
  build:
    name: Build the optimized library files
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install
        run: docker-compose run --rm --user root -T npm install
      - name: Build
        run: docker-compose run --rm --user root -T npm run build
