name: E2E

on:
  pull_request:
    branches:
      - development

jobs:
  e2e:
    name: End-to-end tests
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Dependencies install
        run: npm install
      - name: Build
        run: npm run build
      - name: Tarball
        run: npm pack
      - name: Rename
        run: mv *.tgz esgi-stylelint-config.tgz
      - name: Package install
        run: npm --prefix e2e install ./esgi-stylelint-config.tgz
      - name: List binaries
        run: ls -alh e2e/node_modules/.bin
      - name: Binary test
        run: node e2e/node_modules/.bin/esgi-stylelint index.bad.css
      - name: Stylelint
        run: npm --prefix e2e run stylelint
      - name: Diff
        run: 'diff --ignore-all-space e2e/index.bad.css e2e/index.good.css || exit 1'
