name: E2E

on:
  pull_request:
    branches:
      - development

jobs:
  e2e:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node: ["8.0.0", "9.0.0", "10.0.0", "11.0.0", "12.0.0", "13.0.0", "14.0.0", "15.0.0", "16.0.0"]
    name: End-to-end tests for Node ${{ matrix.node }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: Dependencies install
        run: npm install
      - name: Build
        run: npm run build
      - name: Tarball
        run: npm pack
      - name: Rename
        run: mv *.tgz esgi-stylelint-config.tgz
      - name: Package install
        run: npm --prefix e2e install ./esgi-stylelint-config.tgz
      - name: Binary
        run: node e2e/node_modules/.bin/esgi-stylelint e2e/index.good.css
      - name: StyleLint
        run: npm --prefix e2e run stylelint
      - name: Diff
        run: 'diff --ignore-all-space e2e/index.bad.css e2e/index.good.css || exit 1'
