name: E2E

on:
  pull_request:
    branches:
      - development

jobs:
  e2e:
    name: End-to-end tests
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install
        run: docker-compose run --rm --user root -T npm install
      - name: Build
        run: docker-compose run --rm --user root -T npm run build
      - name: Tarball
        run: docker-compose run --rm --user root -T npm pack
      - name: Rename
        run: docker-compose run --rm --user root -T bash 'mv *.tgz package.tgz'
      - name: Install
        run: docker-compose run --rm --user root -T npm install --prefix e2e ./package.tgz
      - name: Stylelint
        run: docker-compose run --rm --user root -T npm --prefix e2e run stylelint
      - name: Diff
        run: docker-compose run --rm --user root -T bash 'diff e2e/index.bad.css e2e/index.good.css || exit 1'
      - name: CLI
        run: 'docker-compose run --rm --user root -T npx ./package.tgz e2e/index.bad.css > e2e/output.result.txt'
      - name: Diff
        run: docker-compose run --rm --user root -T bash 'diff e2e/output.expectation.txt e2e/output.result.txt || exit 1'
