name: E2E

on:
  pull_request:
    branches:
      - development

jobs:
  e2e:
    name: End-to-end tests
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Dependencies install
        run: npm install
      - name: Build
        run: npm run build
      - name: Tarball
        run: npm pack
      - name: Rename
        run: mv *.tgz esgi-stylelint-config.tgz
      - name: CLI
        run: 'sudo npm_config_yes=true npx --quiet ./esgi-stylelint-config.tgz e2e/index.bad.css | sudo tee e2e/output.result.txt'
      - name: CLI debug
        run: cat e2e/output.result.txt
      - name: CLI diff
        run: 'cat e2e/ouput.result.txt && diff e2e/output.result.txt e2e/output.expectation.txt'
      - name: Package install
        run: npm install --prefix e2e ./esgi-stylelint-config.tgz
      - name: Stylelint
        run: npm --prefix e2e run stylelint
      - name: Diff
        run: 'diff --ignore-all-space e2e/index.bad.css e2e/index.good.css || exit 1'
